import{s as x,a as P,i}from"./assets/vendor-D0tbaKAu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const y=document.querySelector(".gallery"),f=document.querySelector(".loader-text"),g=document.querySelector(".btn-Load-more"),L=new x(".gallery a",{captionsData:"alt",captionDelay:250,fileExt:"png|jpg|jpeg|gif"});function S(){y.innerHTML=""}function B(r){const e=v(r);y.innerHTML=e,L.refresh()}function $(r){const e=r.hits?r.hits:r,s=v(e);y.insertAdjacentHTML("beforeend",s),L.refresh()}function b(){f&&f.classList.add("loader")}function w(){f&&f.classList.remove("loader")}function c(){g&&g.classList.add("hide-load-moreBtn")}function m(){g&&g.classList.remove("hide-load-moreBtn")}function v(r){return r.map(({largeImageURL:e,webformatURL:s,tags:a,likes:t,views:o,comments:l,downloads:M})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img class="gallery-image" src="${s}" alt="${a}" loading="lazy" />
            </a>
            <ul class="galery-info">
                <li><strong>Likes</strong><br>${t}</li>
                <li><strong>Views</strong><br>${o}</li>
                <li><strong>Comments</strong><br>${l}</li>
                <li><strong>Downloads</strong><br>${M}</li>
            </ul>
        </li>`).join("")}const H=P.create({baseURL:"https://pixabay.com/api/",params:{key:"56127983-233044a9880c0570de7cf761a",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(r,e,s){try{return(await H.get("",{params:{q:r,page:e,per_page:s}})).data}catch(a){throw a}}const h=document.querySelector(".form"),p=document.querySelector(".btn-Load-more");let n=1;const u=15,O=Math.ceil(500/u);let d="";c();h.addEventListener("submit",async r=>{if(r.preventDefault(),S(),n=1,c(),d=document.querySelector("input[name='search-text']").value.trim(),d===""){i.error({message:"Please enter a value to search for!"});return}b();try{const e=await q(d,n,u);if(e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}B(e.hits),e.totalHits>u?m():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"An error occurred while fetching images. Please try again later."})}finally{w(),h.reset()}});p.addEventListener("click",async()=>{if(n>=O)return c(),i.error({position:"topRight",message:"We're sorry, there are no more posts to load"});b(),c();try{n+=1;const r=await q(d,n,u);$(r);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(r.totalHits/u);n>=s?(c(),i.info({message:"We're sorry, but you've reached the end of search results."})):m(),n>1&&(p.textContent="Fetch more posts")}catch(r){console.error(r),m()}finally{w()}});
//# sourceMappingURL=index.js.map
