import{s as M,a as P,i as n}from"./assets/vendor-D0tbaKAu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const h=document.querySelector(".gallery"),d=document.querySelector(".loader-text"),f=document.querySelector(".btn-Load-more"),L=new M(".gallery a",{captionsData:"alt",captionDelay:250,fileExt:"png|jpg|jpeg|gif"});function S(){h.innerHTML=""}function B(r){const e=v(r);h.innerHTML=e,L.refresh()}function $(r){const e=r.hits?r.hits:r,s=v(e);h.insertAdjacentHTML("beforeend",s),L.refresh()}function b(){d&&d.classList.add("loader")}function w(){d&&d.classList.remove("loader")}function c(){f&&f.classList.add("hide-load-moreBtn")}function m(){f&&f.classList.remove("hide-load-moreBtn")}function v(r){return r.map(({largeImageURL:e,webformatURL:s,tags:a,likes:t,views:o,comments:l,downloads:x})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img class="gallery-image" src="${s}" alt="${a}" loading="lazy" />
            </a>
            <ul class="galery-info">
                <li><strong>Likes</strong><br>${t}</li>
                <li><strong>Views</strong><br>${o}</li>
                <li><strong>Comments</strong><br>${l}</li>
                <li><strong>Downloads</strong><br>${x}</li>
            </ul>
        </li>`).join("")}const H=P.create({baseURL:"https://pixabay.com/api/",params:{key:"56127983-233044a9880c0570de7cf761a",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(r,e,s){try{return(await H.get("",{params:{q:r,page:e,per_page:s}})).data}catch(a){throw a}}const y=document.querySelector(".form"),p=document.querySelector(".btn-Load-more");let i=1;const g=15;let u="";c();y.addEventListener("submit",async r=>{if(r.preventDefault(),S(),i=1,c(),u=document.querySelector("input[name='search-text']").value.trim(),u===""){n.error({message:"Please enter a value to search for!"});return}b();try{const e=await q(u,i,g);if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}B(e.hits);const s=Math.ceil(e.totalHits/g);i<s?m():(c(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"An error occurred while fetching images. Please try again later."})}finally{w(),y.reset()}});p.addEventListener("click",async()=>{b(),c();try{i+=1;const r=await q(u,i,g);if(r.hits.length===0){c(),n.info({message:"We're sorry, but you've reached the end of search results."});return}$(r.hits);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(r.totalHits/g);i>=s?(c(),n.info({message:"We're sorry, but you've reached the end of search results."})):m(),i>1&&(p.textContent="Fetch more posts")}catch{n.error({message:"An error occurred while loading more images. Please try again later."}),m()}finally{w()}});
//# sourceMappingURL=index.js.map
